from typing import TypeAlias

Value: TypeAlias = bytes | str | int | float | bool | None | list["Value"] | dict[str, "Value"]
TtlResult: TypeAlias = tuple[Value | None, float | None]

class Revision:
    def __init__(self) -> None: ...

class RevisionedValue:
    def __init__(self) -> None: ...

class CompareAndSwapResult:
    def __init__(self) -> None: ...

class CompareAndDeleteResult:
    def __init__(self) -> None: ...

class DiskStore:
    def __init__(self, path: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class DuckDBStore:
    def __init__(self, path: str | None = None, table_name: str | None = None) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class DynamoDBStore:
    def __init__(self, table_name: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class FileTreeStore:
    def __init__(self, base_path: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class FirestoreStore:
    def __init__(self, project_id: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...

class KeyringStore:
    def __init__(self, service_name: str | None = None) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...

class MemcachedStore:
    def __init__(self, url: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def destroy(self) -> bool: ...

class MemoryStore:
    def __init__(self) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...
    async def get_with_revision(self, key: str, collection: str | None = None) -> RevisionedValue | None: ...
    async def compare_and_swap(
        self, key: str, expected: Revision | None, value: Value, collection: str | None = None, ttl: float | None = None
    ) -> CompareAndSwapResult: ...
    async def compare_and_delete(self, key: str, expected: Revision, collection: str | None = None) -> CompareAndDeleteResult: ...

class MongoDBStore:
    def __init__(self, url: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class NullStore:
    def __init__(self) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class OpenSearchStore:
    def __init__(self, url: str, index_prefix: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class PostgresStore:
    def __init__(self, url: str, table_name: str | None = None) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class RedisStore:
    def __init__(self, url: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...
    async def get_with_revision(self, key: str, collection: str | None = None) -> RevisionedValue | None: ...
    async def compare_and_swap(
        self, key: str, expected: Revision | None, value: Value, collection: str | None = None, ttl: float | None = None
    ) -> CompareAndSwapResult: ...
    async def compare_and_delete(self, key: str, expected: Revision, collection: str | None = None) -> CompareAndDeleteResult: ...

class RocksDBStore:
    def __init__(self, path: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class S3Store:
    def __init__(self, bucket_name: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class SimpleStore:
    def __init__(self) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class SqliteStore:
    def __init__(self, path: str | None = None, table_name: str | None = None) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...

class ValkeyStore:
    def __init__(self, url: str) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...
    async def keys(self, collection: str | None = None, limit: int | None = None) -> list[str]: ...
    async def collections(self, limit: int | None = None) -> list[str]: ...
    async def destroy_collection(self, collection: str) -> bool: ...
    async def destroy(self) -> bool: ...
    async def cull(self) -> None: ...
    async def get_with_revision(self, key: str, collection: str | None = None) -> RevisionedValue | None: ...
    async def compare_and_swap(
        self, key: str, expected: Revision | None, value: Value, collection: str | None = None, ttl: float | None = None
    ) -> CompareAndSwapResult: ...
    async def compare_and_delete(self, key: str, expected: Revision, collection: str | None = None) -> CompareAndDeleteResult: ...

class VaultStore:
    def __init__(self, url: str, token: str, mount_point: str | None = None) -> None: ...
    async def get(self, key: str, collection: str | None = None) -> Value | None: ...
    async def ttl(self, key: str, collection: str | None = None) -> TtlResult: ...
    async def put(self, key: str, value: Value, collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete(self, key: str, collection: str | None = None) -> bool: ...
    async def get_many(self, keys: list[str], collection: str | None = None) -> list[Value | None]: ...
    async def ttl_many(self, keys: list[str], collection: str | None = None) -> list[TtlResult]: ...
    async def put_many(self, keys: list[str], values: list[Value], collection: str | None = None, ttl: float | None = None) -> None: ...
    async def delete_many(self, keys: list[str], collection: str | None = None) -> int: ...

def _encode_entry(value: Value, created_at_millis: int | None, expires_at_millis: int | None) -> bytes: ...
def _decode_entry(encoded: bytes) -> tuple[Value, int | None, int | None]: ...
def _prepare_entry_timestamps(ttl: float | None) -> tuple[int, int | None]: ...
